### ISSUE TITLE
Install docker in bastion host

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/cluster-infrastructure#70]
Hello team,

We are testing the application on bastion host and it's good to have for troubleshooting docker installed on the bastion host. Please install Docker Deamon and Docker CLI in the bastion host and make sure that we are able to run any docker containers.

Steps 
1. Install all packages on bastion host and take a note 
2. After you finish with installation go ahead and create PR 
 
Change this file only 
https://github.com/fuchicorp/cluster-infrastructure/blob/a5c0c098b1666b54db1c4e092417969ba8cc870c/fuchicorp-bastion/fuchicorp-bastion.tf#L31

Thank you

**Comment by LmStripe** [comment]
Hi Team, the reason why this was created was because of ticket #70 (Install docker in bastion host) there was not enough space in the BastionHost that's why we had to create this ticket.
